engine_file:   "/media/F/hbf/YOLOv5-Lite-master/cpp_demo/tensorrt/best_1024.engine"
labels_file:   "/media/F/hbf/YOLOv5-Lite-master/cpp_demo/tensorrt/disease.name"
BATCH_SIZE:    1
INPUT_CHANNEL: 3
IMAGE_WIDTH:   1024
IMAGE_HEIGHT:  1024
obj_threshold: 0.30
nms_threshold: 0.2
strides:       [8, 16, 32]
num_anchors:   [3,  3,  3]
anchors:       [[10,13], [16,30], [33,23], [30,61], [62,45], [59,119], [116,90], [156,198], [373,326]]
